name 'kafka-cluster'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Installs and configures Apache Kafka.'
long_description 'Installs and configures Apache Kafka.'
version '1.0.0'

supports 'centos', '>= 6.0'
supports 'redhat', '>= 6.0'

depends 'java'
depends 'libarchive'
depends 'poise-service'
depends 'zookeeper-cluster'
